title: Deep Breath
description: Genetics Meets Visualization
author: Sleiman Bassim
github: https://github.com/neocruiser
about: I Apply Computational Statistics to Genomic & Genetic Data
avatar_url: /static/img/sleiman.jpg

enableTags: true
tagarray: []

collections:

publications:
  collections_dir: static
  permalink: /publications/:path/

resume:
  collections_dir: static
  permalink: /resume/:path/

project:
  output: true
  permalink: /project/:path/

social:
    - icon: fa-twitter
      link: "https://twitter.com/vizGenetics"
    - icon: fa-linkedin
      link: "https://www.linkedin.com/in/sleimanbassim"
    - icon: fa-github
      link: "https://github.com/neocruiser"

share:
  twitter_username: vizGenetics

urls:
    - text: About Me
      url: /about/
    - text: My Projects
      url: /projects/
    - text: CSS Feed
      url: /feed.xml

url: "https://neocruiser.github.io"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-feed

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
